### PR TITLE
Fix TypeScript Errors in Vanilla Components

### PR DESCRIPTION
**Pull request by cwbuecheler**
### Description
Makes significant changes to the Vanilla Components repo in order to address (and in nearly all cases fix) various TypeScript errors. In a small handful of cases the errors have been suppressed pending some potential changes to the core and react modules that the engineering team handles. I don't think it's worth holding up this PR for that, though, because it touches so many files and we want to avoid conflicts. I have instead created a ticket for myself to reinvestigate those errors after the respective fixes are in place.

In the meantime, this PR mainly adds types to variables that were missing them, but also in a few cases introduces minor code tweaks to help with things like handling possible null/undefined values. I also -- and this was a mistake, I should've done it in a separate PR -- introduced prettier to the repo, so a LOT of files got reformatted. This makes the PR spammier and harder to review than it should be, and I apologize for that.

### Things to look for:
I'd suggest looking at the diffs for the individual commits as it's less overwhelming than looking at the master diff. In most cases you'll see two types of changes: stuff prettier did to adjust code formatting (mostly tabs and carriage returns), and changes to improve typing throughout the repo. The latter are important. The former is not.

Something like 1/3 of all the errors were in two utility files, `downloadAsCSV.ts` and `getStackedChartData.ts`, both of which have been fully updated.

Should be pretty readable but let me know if there are any questions!

### Acceptance Criteria
As long as you have no issues with the code changes, we should be good to go. I've tested anything where I made any actual logic changes, except for downloading CSV data from Pivot Tables, as we appear to have that button disabled in Pivot Tables at the moment (there's no way to make it show up in the builder). If we decide to enable that feature later we'll want to test it, but that may be something we worry about in Remarkable Components.

I requested review from a bunch of folks because a bunch of people have edited this repo and also because I know Harry wanted to see the changes and thought Tom might also have some thoughts.

I think that's everything!

### CODE REVIEW

**Review by mad-raccoon — APPROVED** [review]
regarding this "...as we appear to have that button disabled in Pivot Tables at the moment (there's no way to make it show up in the builder)..."

are you saying because of this ? 

image

**Comment by cwbuecheler** [comment]
@mad-raccoon - Yes, there's no download link in the pivot table and as far as I can tell, no way to enable the download link in its settings in the building. Am I missing something obvious? 😁

**Comment by cwbuecheler** [comment]
@mad-raccoon - turns out enabling the checkbox that then enables the link is done in the code. I'll talk w/ Harry about why it's not enabled for the pivot table and create a ticket for myself if something needs to be worked on.

**Comment by cwbuecheler** [comment]
> > @mad-raccoon - Yes, there's no download link in the pivot table and as far as I can tell, no way to enable the download link in its settings in the builder. Am I missing something obvious? 😁
> 
> The download Icon is shown because of the wrapper 'Container' - this is defines on the vanilla component side.
> 
> The fact that the 'download button' is not shown on the bellow canvas "Custom canvas":
> 
Got it. But I think specifically for the pivot table, there's no CSV download link because there's no code to enable it. For example, the bar chart has this in the inputs:
```
    {
      name: 'enableDownloadAsCSV',
      type: 'boolean',
      label: 'Show download as CSV',
      category: 'Export options',
      defaultValue: true
  }
```
While the pivot table has no such code. So in this screenshot, you can see most components have the button, but the pivot table at the bottom does not. Because it hasn't been enabled in the code.

image

I believe that's intentional but will check w/ Harry

**Comment by mad-raccoon** [comment]
> > > @mad-raccoon - Yes, there's no download link in the pivot table and as far as I can tell, no way to enable the download link in its settings in the builder. Am I missing something obvious? 😁
> > 
> > 
> > The download Icon is shown because of the wrapper 'Container' - this is defines on the vanilla component side.
> > The fact that the 'download button' is not shown on the bellow canvas "Custom canvas":
> 
> Got it. But I think specifically for the pivot table, there's no CSV download link because there's no code to enable it. For example, the bar chart has this in the inputs:
> 
> ```
>     {
>       name: 'enableDownloadAsCSV',
>       type: 'boolean',
>       label: 'Show download as CSV',
>       category: 'Export options',
>       defaultValue: true
>   }
> ```
> 
> While the pivot table has no such code. So in this screenshot, you can see most components have the button, but the pivot table at the bottom does not. Because it hasn't been enabled in the code.
> 
> image
> I believe that's intentional but will check w/ Harry

That code you shared, makes the user able to configure it via the Builder page - that entry is one input field shown on the Widget Configuration modal:

image


This makes is configurable via the Builder - using the configuration modal.

In theory we dont need to specify a input, since we could just hardcode the CSV to be always enabled.

The important part here the ['Container' wrapper ](https://github.com/embeddable-hq/vanilla-components/blob/main/src/components/vanilla/Container.tsx).

Check the difference between this 2 components. One has the wrapper, the other doesnt. 

Table chart( has the 'Container' wrapper):
image


Pivot Table (has no container):
image

**Comment by cwbuecheler** [comment]
@mad-raccoon - Aahhhh, okay. Thanks!

**Pull request merged**
